-- 테이블 컬럼 데이터의 기본값 설정
CREATE TABLE EX_ORDER(
    ORDER_NO NUMBER DEFAULT 0,
    ORDER_DATE DATE DEFAULT SYSDATE
);

INSERT INTO EX_ORDER
VALUES (1, '2024-02-28');

INSERT INTO EX_ORDER(ORDER_NO)
VALUES (11);

INSERT INTO EX_ORDER(ORDER_DATE)
VALUES (SYSDATE);

/*
DELETE FROM : 테이블의 모든 행의 데이터 삭제, 테이블의 크기는 유지
TRUNCATE TABLE : 모든 행의 데이터를 삭제하고 테이블 크기도 감소
DROP TABLE : 테이블 자체를 삭제
*/
DELETE FROM EX_ORDER;
TRUNCATE TABLE EX_ORDER;
DROP TABLE EX_ORDER;

/*
    SEQUENCES : 
    자동 생성되는, 유일한 정수를 반환하는 데이터베이스 객체
    주로 PRIMARY KEY 값을 자동으로 생성할 때 사용
*/

CREATE SEQUENCE SEQ1;

SELECT SEQ1.NEXTVAL FROM DUAL; -- DUAL : SEQUENCE가 존재하는 임시 테이블
SELECT SEQ1.CURRVAL FROM DUAL;


CREATE SEQUENCE SEQ2 INCREMENT BY 2;
SELECT SEQ2.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ3 
    INCREMENT BY 2
    MINVALUE 0;
SELECT SEQ3.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ4
    INCREMENT BY 2
    START WITH 0
    MAXVALUE 10
    MINVALUE -10;
SELECT SEQ4.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ5
    INCREMENT BY 2
    START WITH 0
    MAXVALUE 10
    MINVALUE -10
    CYCLE
    NOCACHE;
SELECT SEQ5.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ6
    INCREMENT BY 2
    START WITH 3
    NOCACHE; -- CACHE : 미리 만들어놓고 안쓰면 숫자만 늘어남
SELECT SEQ6.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ_PK;
CREATE TABLE EX10(
    COL1 NUMBER PRIMARY KEY,
    COL2 VARCHAR2(10)
);

INSERT INTO EX10
VALUES (SEQ_PK.NEXTVAL, 'A');


