-- JOIN : 
-- 두 개 이상의 테이블에서 데이터들을 조합해서 검색하는 방법
-- SELF-JOIN :
-- 하나의 테이블에서 데이터들을 조합해서 검색하는 방법

-- 직원 테이블에서 사번, 이름, 부서번호를 검색
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES;

-- 부서 테이블에서 부서번호, 부서이름 검색
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

-- 직원과 부서 테이블에서 사번, 이름, 부서번호, 부서이름을 검색
SELECT EMPLOYEE_ID, E.LAST_NAME, E.DEPARTMENT_ID, d.department_name
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--ANSI JOIN
SELECT EMPLOYEE_ID, E.LAST_NAME, E.DEPARTMENT_ID, d.department_name
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 유사 컬럼 : ROWNUM
SELECT ROWNUM R, EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;

SELECT A.R, A.EMPLOYEE_ID, A.LAST_NAME
FROM (
SELECT ROWNUM R, EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC
)A
WHERE A.R BETWEEN 1 AND 5;


