
CREATE TABLE EX_HW1(
    CONTACT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(100)
);

CREATE SEQUENCE HW1_SEQ
    START WITH 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;
SELECT HW1_SEQ.NEXTVAL FROM DUAL;

INSERT INTO EX_HW1
VALUES (HW1_SEQ.NEXTVAL, 'MOK', '011-2222-9348', 'test@gmail.com');

INSERT INTO EX_HW1
VALUES (HW1_SEQ.NEXTVAL, 'KIM', '011-3333-9348', 'kim@gmail.com');

INSERT INTO EX_HW1
VALUES (HW1_SEQ.NEXTVAL, 'ÁøÇõ', '011-4444-9348', 'test@naver.com');

SELECT * FROM EX_HW1
ORDER BY CONTACT_ID DESC;

SELECT * FROM EX_HW1
WHERE PHONE LIKE '010%';

UPDATE EX_HW1
SET EMAIL = 'test@gmail.com'
WHERE NAME = 'ÁøÇõ';

DELETE FROM EX_HW1
WHERE EMAIL = 'kim@gmail.com';


